services:
  - type: worker
    name: ShrutiMusicBot
    env: python
    plan: free
    repo: https://github.com/NoxxOP/ShrutiMusic
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python -m ShrutiMusic
    envVars:
      - key: API_ID
        value: "29448785"
        required: true
        description: "Get this value from https://my.telegram.org"
      - key: API_HASH
        value: "599574f6aff0a09ebb76305b58e7e9c2"
        required: true
        description: "Get this value from https://my.telegram.org"
      - key: BOT_TOKEN
        value: ""
        required: true
        description: "A Bot's token from Botfather"
      - key: MONGO_DB_URI
        value: "mongodb+srv://pusers:nycreation@nycreation.pd4klp1.mongodb.net/?retryWrites=true&w=majority&appName=NYCREATION"
        required: true
        description: "Get a mongodb url from https://cloud.mongodb.com."
      - key: OWNER_ID
        value: "7574330905"
        required: true
        description: "The user id of user whom you would like to add as OWNER."
      - key: OWNER_USERNAME
        value: "WTF_WhyMeeh"
        required: true
        description: "The username of the owner (without @)"
      - key: BOT_USERNAME
        value: "ShrutixMusicbot"
        required: true
        description: "The username of your bot (without @)"
      - key: UPSTREAM_REPO
        value: "https://github.com/NoxxOP/ShrutiMusic"
        required: false
        description: "URL of your GitHub repository"
      - key: STRING_SESSION
        value: ""
        required: true
        description: "A Pyrogram v2 String Session from Replit."
      - key: GIT_TOKEN
        value: ""
        required: false
        description: "Your GitHub personal access token (if needed for private repos)"
      - key: HEROKU_API_KEY
        value: ""
        required: false
        description: "Your Heroku account's API key"
      - key: HEROKU_APP_NAME
        value: ""
        required: false
        description: "Your heroku app name"
      - key: LOG_GROUP_ID
        value: "-1002321189618"
        required: true
        description: "Your Log Group ID, add your bot and promote as an admin with full rights!. Do not ever try to put channel ID here."
      - key: SUPPORT_GROUP
        value: "https://t.me/ShrutiBotsupport"
        required: false
        description: "Your support group username (without @)"
      - key: SUPPORT_CHANNEL
        value: "https://t.me/ShrutiBots"
        required: false
        description: "Your support channel username (without @)"
      - key: COOKIES_URL
        value: "Need , IF You Didn't add Cookies file in cookies folder"
        required: false
        description: "An additional API key for your bot (if needed)"
      - key: START_IMG_URL
        value: ""
        required: false
        description: "Image that appears with the /start command"
